stages:
  - baseImages
  - buildImages
  - devImages

before_script:
  - apk add --no-cache bash
  - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN

php:7.4-fpm:
  stage: baseImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh php:7.4-fpm-alpine liteacz/php:7.4-fpm fpm fpm/base/Dockerfile
  only:
    - tags
    - web

php:7.4-fpm-build:
  stage: buildImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh liteacz/php:7.4-fpm liteacz/php:7.4-fpm-build fpm fpm/build/Dockerfile
  only:
    - tags
    - web

php:7.4-fpm-dev:
  stage: devImages
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./build.sh liteacz/php:7.4-fpm-build liteacz/php:7.4-fpm-dev fpm fpm/dev/Dockerfile
  only:
    - tags
    - web
